<StudentEditContent>:
    orientation: "vertical"
    spacing: "12dp"
    size_hint_y: None
    height: 200

    MDTextField:
        id: name
        hint_text: "Имя"
        text: str(root.student.get("name"))

    MDTextField:
        id: phone
        hint_text: "Телефон"
        text: str(root.student.get("phone"))

    MDTextField:
        id: address
        hint_text: "Адрес"
        text: str(root.student.get("address"))
